server:
  port: 8082
  servlet:
    context-path: "/receitasecreta/"

spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5432/receitasecreta
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob.non-contextual-creation: true
        format_sql: true
  flyway:
    enabled: false
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration
    sql-migration-prefix: V
    sql-migration-separator: __
    sql-migration-suffixes: .sql
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 2KB
  output:
    ansi:
      enabled: Always
  mail:
    host: smtp.hostinger.com
    port: 587
    # username e password serão configurados diretamente no MailConfig
    # username: ${EMAIL_USERNAME:}
    # password: ${EMAIL_PASSWORD:}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 30000
          timeout: 30000
          writetimeout: 30000
        debug: true
    test-connection: false

logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO
    br.com.marcosferreira.receitasecreta.api.services: DEBUG

api:
  security:
    token:
      secret: ${JWT_SECRET:batman batman batman}

app:
  frontend:
    url: ${FRONTEND_URL:http://localhost:5173}
  password-reset:
    token-expiry-hours: ${TOKEN_EXPIRY_HOURS:1}
    max-attempts-per-hour: ${MAX_ATTEMPTS_PER_HOUR:3}
    cleanup-interval-hours: ${CLEANUP_INTERVAL_HOURS:24}
  file:
    upload-dir: uploads
    max-size: 10485760  # 10MB
    allowed-extensions: jpg,jpeg,png,webp,gif
  base-url: ${BASE_URL:http://localhost:8082/receitasecreta}
  receita:
    max-imagens: 10
